services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./.streamlit:/app/.streamlit
      - ./logs:/app/logs
    working_dir: /app
    env_file: .env