services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: teste-tecnico
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./.streamlit:/app/.streamlit
      - ./logs:/app/logs
    working_dir: /app
    env_file: .env